let shopItemsData = [
  {
    id: "casual_shirt",
    name: "Casual Shirt",
    price: 45,
    desc: "A comfortable shirt for casual occasions.",
    img: "assets/img-1.jpg",
  },
  {
    id: "office_shirt",
    name: "Office Shirt",
    price: 100,
    desc: "A stylish shirt suitable for office wear.",
    img: "assets/img-2.jpg",
  },
  {
    id: "t_shirt",
    name: "T Shirt",
    price: 25,
    desc: "A classic T-shirt for everyday use.",
    img: "assets/img-3.png",
  },
  {
    id: "mens_suit",
    name: "Mens Suit",
    price: 300,
    desc: "An elegant suit for formal occasions.",
    img: "assets/img-4.jpg",
  },
  {
    id: "mens_tie",
    name: "Mens Tie",
    price: 25,
    desc: "A sophisticated tie to complement your attire.",
    img: "assets/img-5.png",
  },
  {
    id: "casual_shoes",
    name: "Casual shoes",
    price: 200,
    desc: "Comfortable and stylish shoes for everyday wear.",
    img: "assets/img-6.png",
  },
  {
    id: "black_suit",
    name: "Black Suit",
    price: 450,
    desc: "A sleek and stylish black suit for formal events.",
    img: "assets/img-7.png",
  },
  {
    id: "polo_shirt",
    name: "Polo Shirt",
    price: 45,
    desc: "A classic polo shirt for a smart-casual look.",
    img: "assets/img-8.png",
  },
  {
    id: "denim_shirt",
    name: "Denim Shirt",
    price: 85,
    desc: "A trendy denim shirt for a stylish appearance.",
    img: "assets/img-9.png",
  },
  {
    id: "denim_pants",
    name: "Denim Pants",
    price: 120,
    desc: "Comfortable denim pants for a casual yet cool look.",
    img: "assets/img-10.png",
  },
  {
    id: "basic_cap",
    name: "Basic Cap",
    price: 35,
    desc: "A simple and versatile cap to complete your outfit.",
    img: "assets/img-11.png",
  },
  {
    id: "leather_boots",
    name: "Leather Boots",
    price: 350,
    desc: "Stylish and durable leather boots for any occasion.",
    img: "assets/img-12.png",
  },
];
